### ISSUE TITLE
Data Type of MatchId

### ISSUE THREAD

**Issue by MopsiMauser** [HighGroundVision/Daedalus#1]
Hello,

First of all I want to say thanks for this library. It really simplifies my source code.
But I noticed that you use the long data type for match IDs but in the ProtoBuf templates of Steam ulong is used. It can maybe lead to problems in the future.

Best Regards

**Comment by RGBKnights** [comment]
Thanks for the bug report.
This issue has been resolved as of the [nuget version 2.0.17](https://www.nuget.org/packages/HGV.Daedalus/2.0.17).
