### ISSUE TITLE
Missing Backpack Item Slot

### ISSUE THREAD

**Issue by MopsiMauser** [HighGroundVision/Daedalus#2]
Hello,

there was a big patch for Dota 2 recently which added among other things a fourth backpack item slot. This slot is missing in class HGV.Daedalus.GetMatchDetails.Player .

Best Regards

**Comment by RGBKnights** [comment]
Thanks for the bug report.
This issue has been resolved as of the [nuget version 2.0.17](https://www.nuget.org/packages/HGV.Daedalus/2.0.17).
