### ISSUE TITLE
Getting Lane Position

### ISSUE THREAD

**Issue by MopsiMauser** [HighGroundVision/Daedalus#3]
Hello,

this post is rather a question than an actual issue. Is it possible to retrive the lane position(HardCarry, Support,.... etc) of a player with a call to IDotaApiClient.GetMatchDetails(matchId)? I already took a look at https://wiki.teamfortress.com/wiki/WebAPI/GetMatchDetails but I couldn't find any useful information. 

Best Regards

**Comment by MopsiMauser** [comment]
Some additional information: I came up with this question because the OpenDotaApi provides the 2 fields lane and lane_role in their call for recent Matches(but sadly they aren't filled very often) and the steam protobuf templates for CMsgGCMatchDetailsRequest and CMsgGCMatchDetailsResponse respectively provide now (just recently added) a field for the lane position

Best Regards

**Comment by RGBKnights** [comment]
The OpenDotaApi has these details because they parsed the match data. Even then it can be hard to compute these details from the raw data and are hence often missing.

**Comment by RGBKnights** [comment]
My [Crystalys](https://github.com/HighGroundVision/Crystalys) project can get CMsgGCMatchDetailsResponse if that dose indeed have the details you are looking for. But I do not see anything to do with lane around the player. Also, there is currently issues with that project.

**Comment by MopsiMauser** [comment]
ok, thx for the answer. I thought maybe Valve exposes this information via their API after they implemented the Role Search mode
